;;; http-headers.el --- explains the meaning of a HTTP header
;;
;; This file was automatically generated by
;; https://github.com/andreineculau/know-your-http-well
;;
;;; Commentary:
;;; Code goes here:

(defconst http-headers
  '({{ HTTP_HEADERS }}))

;;;###autoload
(defun http-header (header)
  "Display the meaning of a HTTP header"
  (interactive "sEnter HTTP header: ")
  (let* ((lowercased-header (downcase header))
        (found (assoc lowercased-header http-headers)))
    (if found
        (let ((description (car (cdr found))))
          (message
           "%s - HTTP header\n%s"
           lowercased-header (car description) ))
      (message "%s - HTTP header\nUNKNOWN" lowercased-header))
    ))

(provide 'http-headers)

;;; http-headers.el ends here
