;;; http-methods.el --- explains the meaning of a HTTP method
;;
;; This file was automatically generated by
;; https://github.com/andreineculau/know-your-http-well
;;
;;; Commentary:
;;; Code goes here:

(defconst http-methods
  '({{ HTTP_METHODS }}))

;;;###autoload
(defun http-method (method)
  "Display the meaning of a HTTP ethod"
  (interactive "sEnter HTTP method: ")
  (let* ((uppercased-method (upcase method))
        (found (assoc uppercased-method http-methods)))
    (if found
        (let ((description (car (cdr found))))
          (message
           "%s - HTTP method\n%s"
           uppercased-method (car description) ))
      (message "%s - HTTP method\nUNKNOWN" uppercased-method))
    ))

(provide 'http-methods)

;;; http-methods.el ends here
