;;; media-types.el --- Look up the template of a media-type
;;
;; This file was automatically generated by
;; https://github.com/for-GET/know-your-http-well
;;
;;; Commentary:
;;; Code goes here:

(defconst media-types
  '({{ MEDIA_TYPES }}))

;;;###autoload
(defun media-type (media-type)
  "Display the template of a media-type"
  (interactive
   (list (completing-read "Enter media-type: " media-types)))
  (let* ((lowercased-media-type (downcase media-type))
        (found (assoc lowercased-media-type media-types)))
    (if found
        (let ((template (car (cdr found))))
          (message
           "%s - media-type\n%s"
           lowercased-media-type (car template) ))
      (message "%s - media-type\nUNKNOWN" lowercased-media-type))
    ))

(provide 'media-types)

;;; media-types.el ends here
